export const CONFIG = {
  VELLUM_API_KEY: process.env.VELLUM_API_KEY!,
  WORKFLOWID: process.env.WORKFLOWID!,
  ALTWORKFLOWID: process.env.ALTWORKFLOWID!,
  GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY!
};
